dataset: 'EVQA'

choose: "CS"
vqa_root: '../data/root'
anno_root: '../data/root/annotation'
output_dir: "output/EVQA"
retrieval: "../data/root/ques_ids_KB.json"
# t5_path: "../model/T5_base"
t5_path: "output/EVQA/CS/save_model2"
csv_path: '../data/root/E-VQA_data.csv'
save_model: "save_model2"

top_k: 5
question_len: 600
answer_len: 10
image_size: 448

batch_size_train: 4  # 16
batch_size_test: 4   # 32

# optimizer
weight_decay: 0.005  # 0.05
min_lr: 0
init_lr: 1e-5
max_epoch: 50